import AppKit
import EasyEngineCore

/// Fixed safety limits for clipboard payload retention. Policy, not preference.
enum ClipboardLimits {
    static let maximumEventBytes = 10 * 1024 * 1024
    static let maximumRetainedBytes = 100 * 1024 * 1024
    static let maximumPinnedEntries = ClipboardHistory.maximumPinnedEntries
}

/// Type identifiers whose presence marks a pasteboard event as sensitive. These
/// are used by password managers and similar tools; matching events are rejected
/// before any payload byte is read. Not configurable.
enum SensitivePasteboardMarkers {
    static let identifiers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.TransientType",
        "com.agilebits.onepassword",
        "com.lastpass.lastpass",
        "de.dirkholtwick.clipboard.private",
    ]

    static func contains(_ identifiers: [String]) -> Bool {
        identifiers.contains { self.identifiers.contains($0) }
    }
}

/// Phase-one view of the pasteboard: change count and per-item type identifiers
/// only. Sensitive-marker checks run against this before any payload is read.
struct PasteboardDescriptor: Equatable {
    let changeCount: Int
    let items: [PasteboardItemDescriptor]
}

struct PasteboardItemDescriptor: Equatable {
    let typeIdentifiers: [String]
}

/// Phase-two view: the byte payloads the classifier selected.
struct PasteboardSnapshot: Equatable {
    let changeCount: Int
    let items: [PasteboardItemSnapshot]
}

struct PasteboardItemSnapshot: Equatable {
    let representations: [CapturedPasteboardRepresentation]
}

struct CapturedPasteboardRepresentation: Equatable {
    let typeIdentifier: String
    let data: Data
}

/// Narrow seam over `NSPasteboard` so the monitor and classifier can be tested
/// with immutable snapshots and never touch the user's real clipboard.
protocol PasteboardReading: AnyObject {
    var changeCount: Int { get }
    func descriptor() -> PasteboardDescriptor
    func snapshot(selecting typeIdentifiers: [[String]]) -> PasteboardSnapshot
}

/// Production adapter backed by `NSPasteboard.general`.
final class SystemPasteboardReader: PasteboardReading {
    private let pasteboard: NSPasteboard

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    var changeCount: Int {
        pasteboard.changeCount
    }

    func descriptor() -> PasteboardDescriptor {
        let items = pasteboard.pasteboardItems ?? []
        return PasteboardDescriptor(
            changeCount: pasteboard.changeCount,
            items: items.map { item in
                PasteboardItemDescriptor(typeIdentifiers: item.types.map(\.rawValue))
            }
        )
    }

    func snapshot(selecting typeIdentifiers: [[String]]) -> PasteboardSnapshot {
        let items = pasteboard.pasteboardItems ?? []
        var snapshots: [PasteboardItemSnapshot] = []
        for (index, item) in items.enumerated() {
            let wanted = index < typeIdentifiers.count ? typeIdentifiers[index] : []
            var representations: [CapturedPasteboardRepresentation] = []
            for identifier in wanted {
                if let data = item.data(forType: NSPasteboard.PasteboardType(identifier)) {
                    representations.append(CapturedPasteboardRepresentation(typeIdentifier: identifier, data: data))
                }
            }
            snapshots.append(PasteboardItemSnapshot(representations: representations))
        }
        return PasteboardSnapshot(changeCount: pasteboard.changeCount, items: snapshots)
    }
}
